name: afeefa_handloom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  get: 4.6.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  hexcolor: ^2.0.6
  pinput: ^1.2.2
  simple_gradient_text: ^1.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
